### PR TITLE
avoid adding bf16 custom kwargs unless specified by the user

### PR DESCRIPTION
**Pull request by agokrani**

### CODE REVIEW

**Review by WuTheFWasThat — CHANGES_REQUESTED** [review]
ideally this would preserve functionality on platforms where the keyword arguments are fine

**Comment by WuTheFWasThat** [comment]
(linking to https://github.com/openai/weak-to-strong/issues/11)

**Comment by agokrani** [comment]
Hi @WuTheFWasThat,
Not really sure if the above comment is for me to change something or is it just a comment about the functionality? Should we merge this or use other solution proposed by Shrivastava?

**Comment by WuTheFWasThat** [comment]
yes i think that approach is better!

**Pull request closed without merging**
